In [1]:
import pandas as pd
import numpy as np
data=pd.read_excel("BCLS.xlsx",sheet_name="Sheet1")
data

    Rid          age  income student credit_rating Class
0     1        youth    high      no          fair    no
1     2        youth    high      no     excellent    no
2     3  middle_aged    high      no          fair   yes
3     4       senior  medium      no          fair   yes
4     5       senior     low     yes          fair   yes
5     6       senior     low     yes     excellent    no
6     7  middle_aged     low     yes     excellent   yes
7     8        youth  medium      no          fair    no
8     9        youth     low     yes          fair   yes
9    10       senior  medium     yes          fair   yes
10   11        youth  medium     yes     excellent   yes
11   12  middle_aged  medium      no     excellent   yes
12   13  middle_aged    high     yes          fair   yes
13   14       senior  medium      no     excellent    no

In [2]:
i=data.columns
Class=list(data[i[5]])
p_y=(Class.count('yes')/14)
p_n=(Class.count('no')/14)
py=[]
pn=[]
c_n,c_y = [x for _, x in data.groupby(data[i[5]] == 'yes')]

In [3]:
k=1
for j in ['youth','medium','yes','fair']:
    py.append(list(c_y[i[k]]).count(j)/9)
    pn.append(list(c_n[i[k]]).count(j)/5)
    k+=1
print(py)
print('\n')
print(pn)
py.append(p_y)
pn.append(p_n)
print('\n\n')
t_y=t_n=1
for m,n in zip(py,pn):
    t_y*=m
    t_n*=n
if t_y > t_n:
    print("Class: Yes")
else:
    print("Class: No")

[0.2222222222222222, 0.4444444444444444, 0.6666666666666666, 0.6666666666666666]


[0.6, 0.4, 0.2, 0.4]



Class: Yes

In [16]:
import numpy as np
import pandas as pd
dataframe=pd.read_excel('BCLS.xlsx')

i=dataframe.columns
result=['youth','medium','yes','fair']
age=list(dataframe[i[0]])
total_rec=len(age)
n_c,y_c=(dataframe.groupby(i[5]))
no_c=list(n_c)
yes_c=list(y_c)
print(type(no_c))
py=[]
pn=[]
k=1
#q=yes_c('youth')
for j in ['youth','medium','yes','fair']:
    py.append(list(yes_c[k]).count(j)/9)
    pn.append(list(no_c[k].count(j))/5)
    k+=1

<class 'list'>

ValueError: No axis named youth for object type <class 'pandas.core.frame.DataFrame'>